name: SonarCloud

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Run tests
        run: ./gradlew test

      - name: Generate Kover Coverage Report
        run: ./gradlew koverXmlReport

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: "caliki"
          project: "quest_scat_poc"
          token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: >
            -Dsonar.kotlin.coverage.reportPaths=build/reports/kover/report.xml
